// @agent-context: The agent registry — single source of truth for all supported coding agents.
//
// This list mirrors official `npx skills` agent ids and canonical paths from
// vercel-labs/skills, plus compatibility entries for legacy project formats.

use crate::models::{AgentId, AgentInfo, SkillFormat};

fn shared_project_skills_path() -> String {
    "$PROJECT/.agents/skills/**/SKILL.md".to_string()
}

fn shared_global_skills_path() -> String {
    "$HOME/.agents/skills/**/SKILL.md".to_string()
}

pub fn get_agent_registry() -> Vec<AgentInfo> {
    vec![
        AgentInfo {
            id: AgentId::ClaudeCode,
            display_name: "Claude Code".to_string(),
            description: "Anthropic CLI coding agent".to_string(),
            color: "#f28c54".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec![
                "$HOME/.claude/skills/**/SKILL.md".to_string(),
                "$HOME/.claude/commands/*.md".to_string(),
                "$HOME/.claude/settings.json".to_string(),
                "$HOME/.claude/settings.local.json".to_string(),
                shared_global_skills_path(),
            ],
            global_detection_paths: vec![
                "$HOME/.claude".to_string(),
                "$HOME/.agents/skills".to_string(),
            ],
            project_paths: vec![
                "$PROJECT/.claude/skills/**/SKILL.md".to_string(),
                "$PROJECT/.claude/commands/*.md".to_string(),
                "$PROJECT/.claude/settings.json".to_string(),
                "$PROJECT/.claude/settings.local.json".to_string(),
                "$PROJECT/CLAUDE.md".to_string(),
                shared_project_skills_path(),
            ],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Codex,
            display_name: "Codex".to_string(),
            description: "OpenAI terminal coding agent".to_string(),
            color: "#4dc8b0".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec![
                "$HOME/.codex/skills/**/SKILL.md".to_string(),
                "$HOME/.codex/AGENTS.md".to_string(),
                shared_global_skills_path(),
            ],
            global_detection_paths: vec![
                "$HOME/.codex".to_string(),
                "$HOME/.agents/skills".to_string(),
            ],
            project_paths: vec![
                "$PROJECT/.codex/skills/**/SKILL.md".to_string(),
                "$PROJECT/AGENTS.md".to_string(),
                shared_project_skills_path(),
            ],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::OpenCode,
            display_name: "OpenCode".to_string(),
            description: "OpenCode CLI".to_string(),
            color: "#5ab0ff".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec![
                "$HOME/.config/opencode/skills/**/SKILL.md".to_string(),
                shared_global_skills_path(),
            ],
            global_detection_paths: vec![
                "$HOME/.config/opencode".to_string(),
                "$HOME/.agents/skills".to_string(),
            ],
            project_paths: vec![
                "$PROJECT/.opencode/skills/**/SKILL.md".to_string(),
                shared_project_skills_path(),
            ],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::GithubCopilot,
            display_name: "GitHub Copilot".to_string(),
            description: "GitHub coding assistant".to_string(),
            color: "#57a0ff".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec![
                "$HOME/.copilot/skills/**/SKILL.md".to_string(),
                "$HOME/.copilot/skills/**/*.instructions.md".to_string(),
                shared_global_skills_path(),
            ],
            global_detection_paths: vec![
                "$HOME/.copilot".to_string(),
                "$HOME/.agents/skills".to_string(),
            ],
            project_paths: vec![
                "$PROJECT/.github/copilot-instructions.md".to_string(),
                "$PROJECT/.github/instructions/*.instructions.md".to_string(),
                "$PROJECT/.github/copilot/agents/*.md".to_string(),
                shared_project_skills_path(),
            ],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Cursor,
            display_name: "Cursor".to_string(),
            description: "Cursor editor".to_string(),
            color: "#a58cff".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec![
                "$HOME/.cursor/skills/**/SKILL.md".to_string(),
                "$HOME/.cursor/rules/*.mdc".to_string(),
                shared_global_skills_path(),
            ],
            global_detection_paths: vec![
                "$HOME/.cursor".to_string(),
                "$HOME/.agents/skills".to_string(),
            ],
            project_paths: vec![
                "$PROJECT/.cursor/skills/**/SKILL.md".to_string(),
                "$PROJECT/.cursor/rules/*.mdc".to_string(),
                "$PROJECT/.cursorrules".to_string(),
                shared_project_skills_path(),
            ],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Crush,
            display_name: "Crush".to_string(),
            description: "Charmbracelet Crush".to_string(),
            color: "#e08f54".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.config/crush/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.config/crush".to_string()],
            project_paths: vec!["$PROJECT/.crush/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Windsurf,
            display_name: "Windsurf".to_string(),
            description: "Codeium Windsurf".to_string(),
            color: "#49bed9".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec![
                "$HOME/.codeium/windsurf/skills/**/SKILL.md".to_string(),
                "$HOME/.windsurf/global_rules.md".to_string(),
            ],
            global_detection_paths: vec![
                "$HOME/.codeium/windsurf".to_string(),
                "$HOME/.windsurf".to_string(),
            ],
            project_paths: vec![
                "$PROJECT/.windsurf/skills/**/SKILL.md".to_string(),
                "$PROJECT/.windsurf/rules/*.md".to_string(),
                "$PROJECT/.windsurfrules".to_string(),
            ],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Gemini,
            display_name: "Gemini CLI".to_string(),
            description: "Google Gemini CLI".to_string(),
            color: "#d5b347".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec![
                "$HOME/.gemini/skills/**/SKILL.md".to_string(),
                "$HOME/.gemini/GEMINI.md".to_string(),
                shared_global_skills_path(),
            ],
            global_detection_paths: vec![
                "$HOME/.gemini".to_string(),
                "$HOME/.agents/skills".to_string(),
            ],
            project_paths: vec![
                "$PROJECT/.gemini/skills/**/SKILL.md".to_string(),
                "$PROJECT/.gemini/GEMINI.md".to_string(),
                "$PROJECT/GEMINI.md".to_string(),
                shared_project_skills_path(),
            ],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Cline,
            display_name: "Cline".to_string(),
            description: "Cline VS Code agent".to_string(),
            color: "#d082d6".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec![
                "$HOME/.agents/skills/**/SKILL.md".to_string(),
                "$HOME/.cline/skills/**/SKILL.md".to_string(),
            ],
            global_detection_paths: vec![
                "$HOME/.cline".to_string(),
                "$HOME/.agents/skills".to_string(),
            ],
            project_paths: vec![
                shared_project_skills_path(),
                "$PROJECT/.clinerules".to_string(),
                "$PROJECT/.clinerules/*.md".to_string(),
            ],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::RooCode,
            display_name: "Roo Code".to_string(),
            description: "Roo coding agent".to_string(),
            color: "#cf7ca7".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.roo/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.roo".to_string()],
            project_paths: vec![
                "$PROJECT/.roo/skills/**/SKILL.md".to_string(),
                "$PROJECT/.roo/rules/*.md".to_string(),
                "$PROJECT/.roorules".to_string(),
            ],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::ContinueDev,
            display_name: "Continue".to_string(),
            description: "Continue coding assistant".to_string(),
            color: "#5fb77b".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec![
                "$HOME/.continue/skills/**/SKILL.md".to_string(),
                "$HOME/.continue/rules/*.md".to_string(),
            ],
            global_detection_paths: vec!["$HOME/.continue".to_string()],
            project_paths: vec![
                "$PROJECT/.continue/skills/**/SKILL.md".to_string(),
                "$PROJECT/.continue/rules/*.md".to_string(),
            ],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Aider,
            display_name: "Aider".to_string(),
            description: "Aider terminal coding assistant".to_string(),
            color: "#82b36d".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.aider.conf.yml".to_string()],
            global_detection_paths: vec!["$HOME/.aider.conf.yml".to_string()],
            project_paths: vec![
                "$PROJECT/.aider.conf.yml".to_string(),
                "$PROJECT/CONVENTIONS.md".to_string(),
            ],
            format: SkillFormat::Yaml,
        },
        AgentInfo {
            id: AgentId::AmazonQ,
            display_name: "Amazon Q".to_string(),
            description: "AWS Amazon Q".to_string(),
            color: "#d68748".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec![],
            global_detection_paths: vec![],
            project_paths: vec!["$PROJECT/.amazonq/rules/*.md".to_string()],
            format: SkillFormat::RulesDir,
        },
        AgentInfo {
            id: AgentId::JetbrainsAi,
            display_name: "JetBrains AI".to_string(),
            description: "JetBrains IDE AI".to_string(),
            color: "#d46d95".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec![],
            global_detection_paths: vec![],
            project_paths: vec!["$PROJECT/.aiassistant/rules/*.md".to_string()],
            format: SkillFormat::RulesDir,
        },
        AgentInfo {
            id: AgentId::Tabnine,
            display_name: "Tabnine CLI".to_string(),
            description: "Tabnine CLI".to_string(),
            color: "#6f88d9".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.tabnine/agent/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.tabnine".to_string()],
            project_paths: vec![
                "$PROJECT/.tabnine/agent/skills/**/SKILL.md".to_string(),
                "$PROJECT/.tabnine/guidelines/*.md".to_string(),
            ],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::AugmentCode,
            display_name: "Augment".to_string(),
            description: "Augment coding assistant".to_string(),
            color: "#3fa89a".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.augment/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.augment".to_string()],
            project_paths: vec![
                "$PROJECT/.augment/skills/**/SKILL.md".to_string(),
                "$PROJECT/.augment/rules/*.md".to_string(),
            ],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::OpenHands,
            display_name: "OpenHands".to_string(),
            description: "OpenHands coding agent".to_string(),
            color: "#7ea8ff".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.openhands/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.openhands".to_string()],
            project_paths: vec!["$PROJECT/.openhands/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Devin,
            display_name: "Devin for Terminal".to_string(),
            description: "Devin terminal agent".to_string(),
            color: "#7b9ab2".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.config/devin/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.config/devin".to_string()],
            project_paths: vec!["$PROJECT/.devin/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::AiderDesk,
            display_name: "AiderDesk".to_string(),
            description: "AiderDesk".to_string(),
            color: "#89b9a0".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.aider-desk/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.aider-desk".to_string()],
            project_paths: vec!["$PROJECT/.aider-desk/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Amp,
            display_name: "Amp".to_string(),
            description: "Amp coding agent".to_string(),
            color: "#86a8ff".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.config/agents/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.config/amp".to_string()],
            project_paths: vec![shared_project_skills_path()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Antigravity,
            display_name: "Antigravity".to_string(),
            description: "Antigravity agent".to_string(),
            color: "#8ea467".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec![
                "$HOME/.gemini/antigravity/skills/**/SKILL.md".to_string(),
                shared_global_skills_path(),
            ],
            global_detection_paths: vec![
                "$HOME/.gemini/antigravity".to_string(),
                "$HOME/.agents/skills".to_string(),
            ],
            project_paths: vec![shared_project_skills_path()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::OpenClaw,
            display_name: "OpenClaw".to_string(),
            description: "OpenClaw".to_string(),
            color: "#6dbf9f".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec![
                "$HOME/.openclaw/skills/**/SKILL.md".to_string(),
                "$HOME/.clawdbot/skills/**/SKILL.md".to_string(),
                "$HOME/.moltbot/skills/**/SKILL.md".to_string(),
            ],
            global_detection_paths: vec![
                "$HOME/.openclaw".to_string(),
                "$HOME/.clawdbot".to_string(),
                "$HOME/.moltbot".to_string(),
            ],
            project_paths: vec!["$PROJECT/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::CodeArtsAgent,
            display_name: "CodeArts Agent".to_string(),
            description: "Huawei CodeArts Agent".to_string(),
            color: "#7b89d4".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.codeartsdoer/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.codeartsdoer".to_string()],
            project_paths: vec!["$PROJECT/.codeartsdoer/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::CodeBuddy,
            display_name: "CodeBuddy".to_string(),
            description: "CodeBuddy".to_string(),
            color: "#5cb6a7".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.codebuddy/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.codebuddy".to_string()],
            project_paths: vec!["$PROJECT/.codebuddy/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Codemaker,
            display_name: "Codemaker".to_string(),
            description: "Codemaker".to_string(),
            color: "#6ca2c2".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.codemaker/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.codemaker".to_string()],
            project_paths: vec!["$PROJECT/.codemaker/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::CodeStudio,
            display_name: "Code Studio".to_string(),
            description: "Code Studio".to_string(),
            color: "#7099d0".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.codestudio/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.codestudio".to_string()],
            project_paths: vec!["$PROJECT/.codestudio/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::CommandCode,
            display_name: "Command Code".to_string(),
            description: "Command Code".to_string(),
            color: "#8f9cc7".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.commandcode/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.commandcode".to_string()],
            project_paths: vec!["$PROJECT/.commandcode/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Cortex,
            display_name: "Cortex Code".to_string(),
            description: "Cortex Code".to_string(),
            color: "#6f8ea6".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.snowflake/cortex/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.snowflake/cortex".to_string()],
            project_paths: vec!["$PROJECT/.cortex/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::DeepAgents,
            display_name: "Deep Agents".to_string(),
            description: "Deep Agents".to_string(),
            color: "#7b83be".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec![
                "$HOME/.deepagents/agent/skills/**/SKILL.md".to_string(),
                shared_global_skills_path(),
            ],
            global_detection_paths: vec![
                "$HOME/.deepagents".to_string(),
                "$HOME/.agents/skills".to_string(),
            ],
            project_paths: vec![shared_project_skills_path()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Dexto,
            display_name: "Dexto".to_string(),
            description: "Dexto".to_string(),
            color: "#65a8b0".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec![
                "$HOME/.agents/skills/**/SKILL.md".to_string(),
                "$HOME/.dexto/skills/**/SKILL.md".to_string(),
            ],
            global_detection_paths: vec![
                "$HOME/.dexto".to_string(),
                "$HOME/.agents/skills".to_string(),
            ],
            project_paths: vec![shared_project_skills_path()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Droid,
            display_name: "Droid".to_string(),
            description: "Factory Droid".to_string(),
            color: "#7d9f72".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.factory/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.factory".to_string()],
            project_paths: vec!["$PROJECT/.factory/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Firebender,
            display_name: "Firebender".to_string(),
            description: "Firebender".to_string(),
            color: "#cf8557".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec![
                "$HOME/.firebender/skills/**/SKILL.md".to_string(),
                shared_global_skills_path(),
            ],
            global_detection_paths: vec![
                "$HOME/.firebender".to_string(),
                "$HOME/.agents/skills".to_string(),
            ],
            project_paths: vec![shared_project_skills_path()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::ForgeCode,
            display_name: "ForgeCode".to_string(),
            description: "ForgeCode".to_string(),
            color: "#9b7abd".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.forge/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.forge".to_string()],
            project_paths: vec!["$PROJECT/.forge/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Goose,
            display_name: "Goose".to_string(),
            description: "Goose".to_string(),
            color: "#8bb08a".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.config/goose/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.config/goose".to_string()],
            project_paths: vec!["$PROJECT/.goose/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Junie,
            display_name: "Junie".to_string(),
            description: "Junie".to_string(),
            color: "#a17db0".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.junie/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.junie".to_string()],
            project_paths: vec!["$PROJECT/.junie/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::IFlowCli,
            display_name: "iFlow CLI".to_string(),
            description: "iFlow CLI".to_string(),
            color: "#6ba9bf".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.iflow/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.iflow".to_string()],
            project_paths: vec!["$PROJECT/.iflow/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Kilo,
            display_name: "Kilo Code".to_string(),
            description: "Kilo Code".to_string(),
            color: "#75b19a".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.kilocode/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.kilocode".to_string()],
            project_paths: vec!["$PROJECT/.kilocode/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::KimiCli,
            display_name: "Kimi Code CLI".to_string(),
            description: "Kimi Code CLI".to_string(),
            color: "#6d9ad9".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.config/agents/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.kimi".to_string()],
            project_paths: vec![shared_project_skills_path()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::KiroCli,
            display_name: "Kiro CLI".to_string(),
            description: "Kiro CLI".to_string(),
            color: "#7ea6c8".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.kiro/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.kiro".to_string()],
            project_paths: vec!["$PROJECT/.kiro/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Kode,
            display_name: "Kode".to_string(),
            description: "Kode".to_string(),
            color: "#71a0b6".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.kode/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.kode".to_string()],
            project_paths: vec!["$PROJECT/.kode/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::McpJam,
            display_name: "MCPJam".to_string(),
            description: "MCPJam".to_string(),
            color: "#7f9cb8".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.mcpjam/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.mcpjam".to_string()],
            project_paths: vec!["$PROJECT/.mcpjam/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::MistralVibe,
            display_name: "Mistral Vibe".to_string(),
            description: "Mistral Vibe".to_string(),
            color: "#8fa2d2".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.vibe/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.vibe".to_string()],
            project_paths: vec!["$PROJECT/.vibe/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Mux,
            display_name: "Mux".to_string(),
            description: "Mux".to_string(),
            color: "#7ba6a0".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.mux/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.mux".to_string()],
            project_paths: vec!["$PROJECT/.mux/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Neovate,
            display_name: "Neovate".to_string(),
            description: "Neovate".to_string(),
            color: "#79a8bf".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.neovate/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.neovate".to_string()],
            project_paths: vec!["$PROJECT/.neovate/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Pi,
            display_name: "Pi".to_string(),
            description: "Pi agent".to_string(),
            color: "#6f95c8".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.pi/agent/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.pi/agent".to_string()],
            project_paths: vec!["$PROJECT/.pi/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Qoder,
            display_name: "Qoder".to_string(),
            description: "Qoder".to_string(),
            color: "#6c9bb1".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.qoder/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.qoder".to_string()],
            project_paths: vec!["$PROJECT/.qoder/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::QwenCode,
            display_name: "Qwen Code".to_string(),
            description: "Qwen Code".to_string(),
            color: "#69a7b6".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.qwen/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.qwen".to_string()],
            project_paths: vec!["$PROJECT/.qwen/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Replit,
            display_name: "Replit".to_string(),
            description: "Replit".to_string(),
            color: "#f08d4f".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.config/agents/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$PROJECT/.replit".to_string()],
            project_paths: vec![shared_project_skills_path()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::RovoDev,
            display_name: "Rovo Dev".to_string(),
            description: "Rovo Dev".to_string(),
            color: "#6ca3c1".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.rovodev/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.rovodev".to_string()],
            project_paths: vec!["$PROJECT/.rovodev/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Trae,
            display_name: "Trae".to_string(),
            description: "Trae".to_string(),
            color: "#7a9ed1".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.trae/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.trae".to_string()],
            project_paths: vec!["$PROJECT/.trae/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::TraeCn,
            display_name: "Trae CN".to_string(),
            description: "Trae CN".to_string(),
            color: "#8aa0d3".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.trae-cn/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.trae-cn".to_string()],
            project_paths: vec!["$PROJECT/.trae/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Warp,
            display_name: "Warp".to_string(),
            description: "Warp".to_string(),
            color: "#7f7dc8".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.agents/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec![
                "$HOME/.warp".to_string(),
                "$HOME/.agents/skills".to_string(),
            ],
            project_paths: vec![shared_project_skills_path()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Zencoder,
            display_name: "Zencoder".to_string(),
            description: "Zencoder".to_string(),
            color: "#7b94bc".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.zencoder/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.zencoder".to_string()],
            project_paths: vec!["$PROJECT/.zencoder/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Pochi,
            display_name: "Pochi".to_string(),
            description: "Pochi".to_string(),
            color: "#7a9aaf".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.pochi/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.pochi".to_string()],
            project_paths: vec!["$PROJECT/.pochi/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Adal,
            display_name: "AdaL".to_string(),
            description: "AdaL".to_string(),
            color: "#7aa8a3".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.adal/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.adal".to_string()],
            project_paths: vec!["$PROJECT/.adal/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Bob,
            display_name: "IBM Bob".to_string(),
            description: "IBM Bob".to_string(),
            color: "#5e98a8".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec!["$HOME/.bob/skills/**/SKILL.md".to_string()],
            global_detection_paths: vec!["$HOME/.bob".to_string()],
            project_paths: vec!["$PROJECT/.bob/skills/**/SKILL.md".to_string()],
            format: SkillFormat::SkillMd,
        },
        AgentInfo {
            id: AgentId::Universal,
            display_name: "AGENTS.md".to_string(),
            description: "Universal agent instructions".to_string(),
            color: "#7a7fad".to_string(),
            installed: false,
            skill_count: 0,
            global_paths: vec![],
            global_detection_paths: vec![],
            project_paths: vec![
                "$PROJECT/AGENTS.md".to_string(),
                "$PROJECT/AGENTS.override.md".to_string(),
            ],
            format: SkillFormat::PlainMarkdown,
        },
    ]
}
